export const atletas = [
  {
    id: 1,
    name: "DARIO",
    dojo: "Dojo Bushido",
    zone: "CIC Zone Caguas",
    weight: "-60kg",
    gender: "Male",
  },
  {
    id: 2,
    name: "Junior",
    dojo: "Dojo Samurai",
    zone: "CIC Zone San Juan",
    weight: "-66kg",
    gender: "Male",
  },
  {
    id: 3,
    name: "Carlos Mendez",
    dojo: "Dojo Ronin",
    zone: "CIC Zone Ponce",
    weight: "-73kg",
    gender: "Male",
  },
  {
    id: 4,
    name: "Miguel Torres",
    dojo: "Dojo Kenshin",
    zone: "CIC Zone Mayaguez",
    weight: "-81kg",
    gender: "Male",
  },
  {
    id: 5,
    name: "Luis Rodriguez",
    dojo: "Dojo Warrior",
    zone: "CIC Zone Arecibo",
    weight: "-90kg",
    gender: "Male",
  },
  {
    id: 6,
    name: "Pedro Sanchez",
    dojo: "Dojo Dragon",
    zone: "CIC Zone Bayamon",
    weight: "-100kg",
    gender: "Male",
  },
  {
    id: 7,
    name: "Maria Garcia",
    dojo: "Dojo Phoenix",
    zone: "CIC Zone Carolina",
    weight: "-48kg",
    gender: "Female",
  },
  {
    id: 8,
    name: "Ana Martinez",
    dojo: "Dojo Sakura",
    zone: "CIC Zone Guaynabo",
    weight: "-52kg",
    gender: "Female",
  },
  {
    id: 9,
    name: "Sofia Lopez",
    dojo: "Dojo Lotus",
    zone: "CIC Zone Trujillo Alto",
    weight: "-57kg",
    gender: "Female",
  },
  {
    id: 10,
    name: "Isabella Diaz",
    dojo: "Dojo Tiger",
    zone: "CIC Zone Caguas",
    weight: "-63kg",
    gender: "Female",
  },
  {
    id: 11,
    name: "Valentina Cruz",
    dojo: "Dojo Eagle",
    zone: "CIC Zone San Juan",
    weight: "-70kg",
    gender: "Female",
  },
  {
    id: 12,
    name: "Camila Rivera",
    dojo: "Dojo Falcon",
    zone: "CIC Zone Ponce",
    weight: "-78kg",
    gender: "Female",
  },
]

export const categoriaPeso = [
  { id: 1, name: "-60kg", gender: "Male" },
  { id: 2, name: "-66kg", gender: "Male" },
  { id: 3, name: "-73kg", gender: "Male" },
  { id: 4, name: "-81kg", gender: "Male" },
  { id: 5, name: "-90kg", gender: "Male" },
  { id: 6, name: "-100kg", gender: "Male" },
  { id: 7, name: "+100kg", gender: "Male" },
  { id: 8, name: "-48kg", gender: "Female" },
  { id: 9, name: "-52kg", gender: "Female" },
  { id: 10, name: "-57kg", gender: "Female" },
  { id: 11, name: "-63kg", gender: "Female" },
  { id: 12, name: "-70kg", gender: "Female" },
  { id: 13, name: "-78kg", gender: "Female" },
  { id: 14, name: "+78kg", gender: "Female" },
]
